### ISSUE TITLE
Failed to find nms implementation for: interface rpgdrops.m.F

### ISSUE THREAD

**Issue by mareanc** [PluginBugs/Issues-RPGDrops#3]
### Terms

- [X] I'm using the very latest version of RPGDrops and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-RPGDrops/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### What happened?

Error on loading plugin Failed to find nms implementation for: interface rpgdrops.m.F

### Steps to reproduce the issue

Add the plugin to the server
Start the server

### Server version

1.20.1 paper

### RPGDrops Version

1.0-release-2

### ProtocolLib Version

5.3.0-SNAPSHOT-716

### LoneLibs Version

1.0.54

### FULL server log

[latest.log](https://github.com/user-attachments/files/15842655/latest.log)

### Error (optional)

```shell
[19:26:16 INFO]: [RPGDrops] Enabling RPGDrops v1.0-release-2
[19:26:16 ERROR]: [RPGDrops] Failed to find nms implementation for: interface rpgdrops.m.F

        at org.bukkit.plugin.SimplePluginManager.
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register rpgdrops.m.d@31ea86b4 while not e
[19:26:16 INFO]: [Blue Slime Core] Detected server as regular SpigotMC/PaperMC (not Folia)
[19:26:16 INFO]: [Blue Slime Core] Successfully loaded 2 language(s).
[19:26:16 INFO]: [Blue Slime Core] Enabling BlueSlimeCore v2.9.5.426
[19:26:16 INFO]: [UncraftQuartz] UncraftQuartz Enabled!
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
java.lang.RuntimeException: null
[19:26:16 ERROR]: Error occurred (in the plugin loader) while disabling RPGDrops v1.0-release-2 (Is it up to date?)
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
nabled
enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[19:26:16 ERROR]: Error occurred while enabling RPGDrops v1.0-release-2 (Is it up to date?)
Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:26:16 INFO]: [UncraftQuartz] Enabling UncraftQuartz v1.0
        at rpgdrops.m.j.a(SourceFile:138) ~[RPGDrops_1.0-release-2 (1).jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.registerEvents(PaperPluginManagerImpl.java:131) ~[paper-1.20.1.jar:git-Paper-196]
        at rpgdrops.m.j.a(SourceFile:46) ~[RPGDrops_1.0-release-2 (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-
[19:26:16 INFO]: [RPGDrops] Disabling RPGDrops v1.0-release-2
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:670) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at rpgdrops.m.d.<init>(SourceFile:59) ~[RPGDrops_1.0-release-2 (1).jar:?]
        at dev.lone.rpgdrops.Main.onDisable(SourceFile:37) ~[RPGDrops_1.0-release-2 (1).jar:?]
1.jar:git-Paper-196]
        at dev.lone.rpgdrops.Main.onEnable(SourceFile:30) ~[RPGDrops_1.0-release-2 (1).jar:?]
        at rpgdrops.m.G.a(SourceFile:48) ~[RPGDrops_1.0-release-2 (1).jar:?]
        at rpgdrops.m.G.<init>(SourceFile:31) ~[RPGDrops_1.0-release-2 (1).jar:?]
        at rpgdrops.m.j.a(SourceFile:37) ~[RPGDrops_1.0-release-2 (1).jar:?]
        at rpgdrops.m.d.a(SourceFile:53) ~[RPGDrops_1.0-release-2 (1).jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.registerEvents(PaperEventManager.java:80) ~[paper-1.20.1.jar:git-Paper-196]
```

**Comment by mareanc** [comment]
any news?

**Comment by VacAge** [comment]
1.20.1 not support version

**Comment by mareanc** [comment]
really?
✅ Compatible with 1.19.4, 1.20.1, 1.20.2, 1.20.4, 1.20.6
⚠️Not compatible with 1.19.3 and lower versions! (both client and server). Support can't be added.

so why I found this on spigot plugin page

**Comment by VacAge** [comment]
> really? ✅ Compatible with 1.19.4, 1.20.1, 1.20.2, 1.20.4, 1.20.6 ⚠️Not compatible with 1.19.3 and lower versions! (both client and server). Support can't be added.
> 
> so why I found this on spigot plugin page

https://builtbybit.com/resources/rpgdrops.35127/

**Comment by VacAge** [comment]
I do not know where you got this information.

**Comment by VacAge** [comment]
> really? ✅ Compatible with 1.19.4, 1.20.1, 1.20.2, 1.20.4, 1.20.6 ⚠️Not compatible with 1.19.3 and lower versions! (both client and server). Support can't be added.
> 
> so why I found this on spigot plugin page

I do not know where you got this information.

**Comment by mareanc** [comment]
Nice, well I don't use that shit, I bought from spigot, on spigot check what is says
https://www.spigotmc.org/resources/rpgdrops.114942/

Anyway seems like issues are still unresolved, I bought this and I can't use it from day 1

**Comment by VacAge** [comment]
All sites are good. There are no bad sites, there are no bad ones. It's your own choice. The plugin developer just made a mistake in the description. Choose the expression you use, and wait until your problem and mine are solved.

**Comment by mareanc** [comment]
> All sites are good. There are no bad sites, there are no bad ones. It's your own choice. The plugin developer just made a mistake in the description. Choose the expression you use, and wait until your problem and mine are solved.

Let me guess are you his lawyer or what, shut up and see your own road my brother,  I've asked for this fix for some time, dev is not even aware how broken this plugin is

**Comment by VacAge** [comment]
Cry. I keep you informed, "brother", look at the closed problems of the plugin and you can see that I already wrote about the problems when the plugin was just released. And yes, the developer is not promoting it so quickly, unfortunately, but I will still wait for fixes.
Bye
