### ISSUE TITLE
 [RPGDrops] Failed to find nms implementation for: interface rpgdrops.m.F

### ISSUE THREAD

**Issue by Unmegv2** [PluginBugs/Issues-RPGDrops#5]
### Terms

- [X] I'm using the very latest version of RPGDrops and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-RPGDrops/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/chestpreview/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

un_meg

### What happened?

I tried to launch plugin, but it doesn't run  

### Steps to reproduce the issue

installed plugins, that server need to run
copied to plugins folder
restarted server

I tried to change java version, but it didn't help me.
P.S. I use java 19

### Server version

Current: git-Purpur-2062 (MC: 1.20.1)*
* You are running the latest version

### RPGDrops Version

RPGDrops_1.0-release-2.jar

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.56

### Error (optional)

```shell
[RPGDrops] Failed to find nms implementation for: interface rpgdrops.m.F
[13:27:55 ERROR]: Error occurred while enabling RPGDrops v1.0-release-2 (Is it up to date?)
java.lang.RuntimeException: null
        at rpgdrops.m.j.a(SourceFile:138) ~[RPGDrops_1.0-release-2.jar:?]
        at rpgdrops.m.j.a(SourceFile:46) ~[RPGDrops_1.0-release-2.jar:?]
        at rpgdrops.m.j.a(SourceFile:37) ~[RPGDrops_1.0-release-2.jar:?]
        at rpgdrops.m.G.<init>(SourceFile:31) ~[RPGDrops_1.0-release-2.jar:?]
        at rpgdrops.m.G.a(SourceFile:48) ~[RPGDrops_1.0-release-2.jar:?]
        at dev.lone.rpgdrops.Main.onEnable(SourceFile:30) ~[RPGDrops_1.0-release-2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:656) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[13:27:55 INFO]: [RPGDrops] Disabling RPGDrops v1.0-release-2
[13:27:55 ERROR]: Error occurred (in the plugin loader) while disabling RPGDrops v1.0-release-2 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register rpgdrops.m.d@1ed8ac7 while not enabled
        at io.papermc.paper.plugin.manager.PaperEventManager.registerEvents(PaperEventManager.java:80) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.registerEvents(PaperPluginManagerImpl.java:131) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:674) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at rpgdrops.m.d.<init>(SourceFile:59) ~[RPGDrops_1.0-release-2.jar:?]
        at rpgdrops.m.d.a(SourceFile:53) ~[RPGDrops_1.0-release-2.jar:?]
        at dev.lone.rpgdrops.Main.onDisable(SourceFile:37) ~[RPGDrops_1.0-release-2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:656) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by LoneDev6** [comment]
Update to 1.20.2, 1.20.4 or 1.20.6 or 1.21.1
